ALTER TABLE "StoreSettings"
ADD COLUMN "productCacheSeconds" INTEGER NOT NULL DEFAULT 900,
ADD COLUMN "collectionCacheSeconds" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN "categoryCacheSeconds" INTEGER NOT NULL DEFAULT 300,
ADD COLUMN "storeSettingsCacheSeconds" INTEGER NOT NULL DEFAULT 300;
